name: Safe secret-check
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether ALCHEMY_API_KEY is present (safe)
        run: |
          if [ -n "${{ secrets.ALCHEMY_API_KEY }}" ]; then
            echo "ALCHEMY_API_KEY: SET"
            # Optionally show length only (not the secret itself)
            echo "ALCHEMY_API_KEY length: ${#ALCHEMY_API_KEY}"
          else
            echo "ALCHEMY_API_KEY: NOT SET"
          fi
        env:
          # expose the secret into shell env so ${#ALCHEMY_API_KEY} can measure length
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
